### ISSUE TITLE
Got error "not configured to use Savvy" despite init command being in .bashrc

### ISSUE THREAD

**Issue by tmeijn** [getsavvyinc/savvy-cli#118]
Hi, I tried to use the tool, but particularyl the runbook functionality is broken for me. If I execute `savvy run` I get the example runbooks, but if I select a run book, I get the error message:

```shell
 Your shell is not configured to use Savvy. Please run the following commands:

> echo 'eval "$(savvy init bash)"' >> ~/.bashrc
> source ~/.bashrc
```

This line is already present, last line of rc file:

```shell
❯ cat .bashrc | grep savvy
eval "$(savvy init bash)"
```

Running in debug mode doesn't provide me with any additional output.

Let me know if you need anything else!

**Comment by joshi4** [comment]
Sorry for the trouble using savvy. 


Do you get the same error if you try it in a new terminal tab or after you run `exec bashrc`? 

Does savvy record or savvy record history work for you?

**Comment by joshi4** [comment]
cc @tmeijn 

are you still having the issue?

**Comment by joshi4** [comment]
@tmeijn closing the issue.

Feel free to reopen if you're still running into the issue

**Comment by tmeijn** [comment]
[Recording of me trying `savvy`](https://github.com/user-attachments/assets/359535e4-17d8-4f3c-a7a8-e2c0c887d54d)

Hey @joshi4, sorry to get back to you so late. Just now made time to try it again. As you can see in the video it is still not working on latest version.

```shell
❯ savvy version
version: 0.14.2
```

I do however got a lot of stuff going on with `atuin`, `starship`, etc. being installed.

You can checkout my [`.bashrc`](https://gitlab.com/el-capitano/dotfiles/-/blob/e9247cd041689a18f4c9a195aa11fbbd0e83cc92/chezmoi/dot_bashrc) to see if you can find anything missing? 🤔 

Let me know what other information I can give you to debug this. 😄

**Comment by joshi4** [comment]
@tmeijn thanks for getting back to me. 

reopening...

**Comment by joshi4** [comment]
From looking at your bashrc my best guess is that 

`if command -v savvy &> /dev/null; then eval "$(savvy init bash)"; fi` is not executing `savvy init bash`. 

I don't see where you add Savvy to your PATH in your bashrc file.

Could you share the output of  `which savvy`?

**Comment by tmeijn** [comment]
Hey thanks again for looking into this!

I made another recording to show the problem and troubleshooting better:


https://github.com/user-attachments/assets/3733e573-f3a7-4142-982e-7e52bb002706



It seems though that `atuin` and `savvy` are interfering with each other. If I put `atuin init` before `savvy init` it seems like savvy is silently failing and doesn't execute the rest of my `.bashrc`.

The workaround that seems to work for me is swapping these programs so that `atuin init` is executed after `savvy init`.

**Comment by joshi4** [comment]
@tmeijn Thanks for your video and narrowing it down to `atuin`. 

I was able to replicate the issue and push out a fix. 

Here's  some detail about what triggered the original problem and my propsed fix. 

Savvy relies on bash-preexec.sh to setup pre_cmd and pre_exec hooks in
bash.

Users may rely on multiple other tools(atuin, starship, etc) that
install and setup bash-preexec.sh.

In such cases,  a user's bashrc may initialize bash-preexec before running: `eval $(savvy init
bash)`

In that case [bash-preexec.sh](https://github.com/getsavvyinc/savvy-cli/blob/8c6a834c5a140b83cc77c788e40738f510af7c12/cmd/setup/bash-preexec.sh#L52)
avoids duplicate inclusion and returns early.

As a result, none of Savvy's custom hooks are evaluated and user's get
an error messasge "not configured to use Savvy" when trying to
record/run runbooks.

This commit fixes the above issue by separating initializing
bash-preexec from adding savvy's shell hooks.


-----

You'll need to upgrade to the latest version of the CLI to pull in the fix: `savvy upgrade` should do the trick. 

Let me know if you continue to run into the error after upgrading.

**Comment by tmeijn** [comment]
```shell
❯ savvy version
version: 0.14.5
```

Can confirm that this works, thanks! Now I can actually start to learn and play with `savvy`! 😄
