### ISSUE TITLE
Local LLMs Support

### ISSUE THREAD

**Issue by av** [getsavvyinc/savvy-cli#127]
Hi, thanks for building and opening Savvy!

Is there any way I can configure it to use a locally-running LLM? With OpenAI-compatible API or otherwise.

Thanks!

**Comment by joshi4** [comment]
Curious about your use case for local LLMs vs OpenAI ?

**Comment by av** [comment]
Usage in no-network conditions, data protection, ability to choose specific models for specific kind of workload (for example fine-tuned)

Nothing unique, just a "local LLM" use-case

**Comment by joshi4** [comment]
Thanks for sharing! 

Local Redaction and support for local LLMs is planned and I'm tracking it on our public feedback board [here](https://savvy.featurebase.app/?b=66a299f74c55240443f380de)

**Comment by joshi4** [comment]
Hi @av, 

quick update: 

I've moved away from using OpenAI for generating runbooks and we now use Llama3.1 hosted on Groq. 

Savvy ask/explain still uses GPT4-o for now.

**Comment by joshi4** [comment]
@sjuxax and @av  getting started on this - should have something for y'all to try v soon.

**Comment by joshi4** [comment]
@sjuxax and @av you can now BYO LLM with Savvy's CLI.  See the docs here: https://docs.getsavvy.so/guides/byo_llm/

Implemented in #154
